json.id rental.id
json.user_id rental.user_id
json.address rental.address
json.city rental.city
json.state rental.state
json.price rental.price
json.description rental.description
json.total_occupancy rental.total_occupancy
json.total_bathrooms rental.total_bathrooms
json.total_bed_rentals rental.total_bed_rentals
